/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author L-SOFTWARE
 */
public class boton extends javax.swing.JFrame
{

    /**
     * Creates new form boton
     */
    public boton()
    {
        initComponents();
        ImageIcon image11= new ImageIcon(getClass().getResource("/imagenes/menu.png"));
Icon fondo1= new     ImageIcon(image11.getImage().getScaledInstance(butt.getWidth(),butt.getHeight(),Image.SCALE_DEFAULT));
butt.setIcon(fondo1);
this.repaint();
        butt.setOpaque(true);
        butt.setBorder(null);
        butt.setBorderPainted(false);
        butt.setContentAreaFilled(false);
        butt.setOpaque(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        butt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                buttMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                buttMouseExited(evt);
            }
        });
        butt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(butt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(butt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttActionPerformed
    {//GEN-HEADEREND:event_buttActionPerformed
      principal p=new principal();
      p.setVisible(true);
    }//GEN-LAST:event_buttActionPerformed

    private void buttMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttMouseExited
    {//GEN-HEADEREND:event_buttMouseExited
 ImageIcon image11= new ImageIcon(getClass().getResource("/imagenes/menu1.png"));
Icon fondo1= new     ImageIcon(image11.getImage().getScaledInstance(butt.getWidth(),butt.getHeight(),Image.SCALE_DEFAULT));
butt.setIcon(fondo1);
this.repaint();
        butt.setOpaque(true);
        butt.setBorder(null);
        butt.setBorderPainted(false);
        butt.setContentAreaFilled(false);
        butt.setOpaque(false);
    }//GEN-LAST:event_buttMouseExited

    private void buttMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_buttMouseEntered
    {//GEN-HEADEREND:event_buttMouseEntered
        ImageIcon image11= new ImageIcon(getClass().getResource("/imagenes/menu.png"));
Icon fondo1= new     ImageIcon(image11.getImage().getScaledInstance(butt.getWidth(),butt.getHeight(),Image.SCALE_DEFAULT));
butt.setIcon(fondo1);
this.repaint();
        butt.setOpaque(true);
        butt.setBorder(null);
        butt.setBorderPainted(false);
        butt.setContentAreaFilled(false);
        butt.setOpaque(false);
    }//GEN-LAST:event_buttMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(boton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new boton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt;
    // End of variables declaration//GEN-END:variables
}