/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Métodos.ManipulaDBC;
import cjb.ci.Validaciones;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.InputMap;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.KeyStroke;

/**
 *
 * @author uriel
 */
public class Ventana_Paciente extends javax.swing.JFrame {
Connection con;
    /**
     * Creates new form PacienteV1
     */
    public Ventana_Paciente() {
        initComponents();
        
        
        //this.setExtendedState(MAXIMIZED_BOTH);        
        this.setLocationRelativeTo(this);          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        jPanelPerfil = new javax.swing.JPanel();
        jLabelFotoPefil = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jPanelDiseño1 = new javax.swing.JPanel();
        jPanelDiseño2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAPaterno = new javax.swing.JLabel();
        jLabelAMaterno = new javax.swing.JLabel();
        jLabelCurp = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldAPaterno = new javax.swing.JTextField();
        jTextFieldAMaterno = new javax.swing.JTextField();
        jTextFieldCurp = new javax.swing.JTextField();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelEncabezado = new javax.swing.JPanel();
        jButtonEsconder = new javax.swing.JButton();
        jPanelDiseño3 = new javax.swing.JPanel();
        jButtonminimizar = new javax.swing.JButton();
        jButtoncerrar = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jButtonregresar = new javax.swing.JButton();
        jScrollPaneHistorial = new javax.swing.JScrollPane();
        jPanelHistorial = new javax.swing.JPanel();
        jScrollBarHistorial = new javax.swing.JScrollBar();
        jSeparator25 = new javax.swing.JSeparator();
        jLabelTitulo2 = new javax.swing.JLabel();
        jPanelDiseño8 = new javax.swing.JPanel();
        jPanelDiseño4 = new javax.swing.JPanel();
        jLabelTitulo3 = new javax.swing.JLabel();
        jLabelTitulo4 = new javax.swing.JLabel();
        jPanelDiseño6 = new javax.swing.JPanel();
        jPanelDiseño7 = new javax.swing.JPanel();
        jLabelNomCompPac = new javax.swing.JLabel();
        jLabelFolio = new javax.swing.JLabel();
        jLabelCurp2 = new javax.swing.JLabel();
        jLabelFecNac = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelReligion = new javax.swing.JLabel();
        jLabelColonia = new javax.swing.JLabel();
        jLabelMunicipio = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelCalle = new javax.swing.JLabel();
        jButtonInsertImg = new javax.swing.JButton();
        jLabelTitulo5 = new javax.swing.JLabel();
        jLabelTrabajo = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelNomComDoc = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jTextFieldTelefonoDoc = new javax.swing.JTextField();
        jTextFieldNomCompPac = new javax.swing.JTextField();
        jTextFieldFolio = new javax.swing.JTextField();
        jTextCurp2 = new javax.swing.JTextField();
        jTextFieldFecNac = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jTextFielTelefono = new javax.swing.JTextField();
        jTextFieldMunicipio = new javax.swing.JTextField();
        jTextFieldColonia = new javax.swing.JTextField();
        jTextFieldCalle = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldReligion = new javax.swing.JTextField();
        jTextFieldTrabajo = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jPanelDiseño5 = new javax.swing.JPanel();
        jLabelTitulo6 = new javax.swing.JLabel();
        jPanelDiseño9 = new javax.swing.JPanel();
        jPanelDiseño10 = new javax.swing.JPanel();
        jComboBoxDoctores = new javax.swing.JComboBox<>();
        jLabelTipSangre = new javax.swing.JLabel();
        jLabelCedulaProfesional = new javax.swing.JLabel();
        jLabelDireccionDoc = new javax.swing.JLabel();
        jLabelTitulo8 = new javax.swing.JLabel();
        jLabelEdadDoc = new javax.swing.JLabel();
        jLabelSexoDoc = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jTextFieldTipSangre = new javax.swing.JTextField();
        jPanelDiseño11 = new javax.swing.JPanel();
        jLabelTitulo7 = new javax.swing.JLabel();
        jPanelDiseño12 = new javax.swing.JPanel();
        jPanelDiseño13 = new javax.swing.JPanel();
        jLabelTitulo12 = new javax.swing.JLabel();
        jLabelTelefonoDoc = new javax.swing.JLabel();
        jLabelTitulo10 = new javax.swing.JLabel();
        jLabelTitulo9 = new javax.swing.JLabel();
        jLabelTitulo11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaAntPer = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaAntFam = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaAntPat = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextAreaAntQuir = new javax.swing.JTextArea();
        jButtonModificar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jTextFieldNomComDoc1 = new javax.swing.JTextField();
        jTextFieldCedulaProfesional = new javax.swing.JTextField();
        jTextFieldDireccionDoc = new javax.swing.JTextField();
        jTextFieldEdadDoc = new javax.swing.JTextField();
        jTextFieldSexoDoc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGeneral.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 201, 232)));
        jPanelPerfil.setPreferredSize(new java.awt.Dimension(263, 720));
        jPanelPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFotoPefil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono cuenta-redonda-con-usuario-dentro.png"))); // NOI18N
        jLabelFotoPefil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPerfil.add(jLabelFotoPefil, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, 160));

        jLabelTitulo1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(181, 77, 180));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("PERFIL ");
        jPanelPerfil.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, 40));

        jPanelDiseño1.setBackground(new java.awt.Color(232, 201, 232));

        jPanelDiseño2.setBackground(new java.awt.Color(96, 83, 150));

        javax.swing.GroupLayout jPanelDiseño2Layout = new javax.swing.GroupLayout(jPanelDiseño2);
        jPanelDiseño2.setLayout(jPanelDiseño2Layout);
        jPanelDiseño2Layout.setHorizontalGroup(
            jPanelDiseño2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanelDiseño2Layout.setVerticalGroup(
            jPanelDiseño2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelDiseño1Layout = new javax.swing.GroupLayout(jPanelDiseño1);
        jPanelDiseño1.setLayout(jPanelDiseño1Layout);
        jPanelDiseño1Layout.setHorizontalGroup(
            jPanelDiseño1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiseño1Layout.createSequentialGroup()
                .addComponent(jPanelDiseño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDiseño1Layout.setVerticalGroup(
            jPanelDiseño1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiseño1Layout.createSequentialGroup()
                .addComponent(jPanelDiseño2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        jPanelPerfil.add(jPanelDiseño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 40, 140));

        jLabelNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre.setText("Nombre(s):");
        jPanelPerfil.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 30));

        jLabelAPaterno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAPaterno.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno.setText("A. Paterno:");
        jPanelPerfil.add(jLabelAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, 30));

        jLabelAMaterno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAMaterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAMaterno.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAMaterno.setText("A. Materno:");
        jPanelPerfil.add(jLabelAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 30));

        jLabelCurp.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCurp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCurp.setForeground(new java.awt.Color(96, 83, 150));
        jLabelCurp.setText("CURP:");
        jPanelPerfil.add(jLabelCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 90, 30));

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 210, 30));

        jTextFieldAPaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldAPaterno.setBorder(null);
        jTextFieldAPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAPaternoActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jTextFieldAPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 210, 30));

        jTextFieldAMaterno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldAMaterno.setBorder(null);
        jTextFieldAMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAMaternoActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jTextFieldAMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 210, 30));

        jTextFieldCurp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldCurp.setBorder(null);
        jTextFieldCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCurpActionPerformed(evt);
            }
        });
        jPanelPerfil.add(jTextFieldCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 210, 30));

        jButtonConsultar.setBackground(new java.awt.Color(232, 201, 232));
        jButtonConsultar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(96, 83, 150));
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConsultar.setBorderPainted(false);
        jButtonConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConsultar.setFocusPainted(false);
        jPanelPerfil.add(jButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 160, 40));

        jButtonAgregar.setBackground(new java.awt.Color(232, 201, 232));
        jButtonAgregar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(96, 83, 150));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelPerfil.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 160, 40));

        jSeparator1.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator1.setForeground(new java.awt.Color(232, 201, 232));
        jPanelPerfil.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator2.setForeground(new java.awt.Color(232, 201, 232));
        jPanelPerfil.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 210, 10));

        jSeparator3.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator3.setForeground(new java.awt.Color(232, 201, 232));
        jPanelPerfil.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 210, 10));

        jSeparator4.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator4.setForeground(new java.awt.Color(232, 201, 232));
        jPanelPerfil.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 210, -1));

        jPanelGeneral.add(jPanelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 320, 730));

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEncabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 201, 232)));
        jPanelEncabezado.setForeground(new java.awt.Color(232, 201, 232));

        jButtonEsconder.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEsconder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton-de-menu-de-tres-lineas-horizontales.png"))); // NOI18N
        jButtonEsconder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEsconder.setBorderPainted(false);
        jButtonEsconder.setFocusCycleRoot(true);
        jButtonEsconder.setFocusPainted(false);
        jButtonEsconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEsconderActionPerformed(evt);
            }
        });

        jPanelDiseño3.setBackground(new java.awt.Color(96, 83, 150));

        jButtonminimizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jButtonminimizar.setBorderPainted(false);
        jButtonminimizar.setContentAreaFilled(false);
        jButtonminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonminimizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jButtoncerrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtoncerrar.setBorder(null);
        jButtoncerrar.setBorderPainted(false);
        jButtoncerrar.setContentAreaFilled(false);
        jButtoncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtoncerrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jButtonInicio.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonInicio.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jButtonregresar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButtonregresar.setBorderPainted(false);
        jButtonregresar.setContentAreaFilled(false);
        jButtonregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonregresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonregresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDiseño3Layout = new javax.swing.GroupLayout(jPanelDiseño3);
        jPanelDiseño3.setLayout(jPanelDiseño3Layout);
        jPanelDiseño3Layout.setHorizontalGroup(
            jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDiseño3Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtoncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanelDiseño3Layout.setVerticalGroup(
            jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiseño3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtoncerrar)
                    .addComponent(jButtonminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEncabezadoLayout = new javax.swing.GroupLayout(jPanelEncabezado);
        jPanelEncabezado.setLayout(jPanelEncabezadoLayout);
        jPanelEncabezadoLayout.setHorizontalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                .addComponent(jButtonEsconder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 853, Short.MAX_VALUE)
                .addComponent(jPanelDiseño3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEncabezadoLayout.setVerticalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDiseño3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonEsconder, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jPanelGeneral.add(jPanelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 60));

        jScrollPaneHistorial.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneHistorial.setBorder(null);
        jScrollPaneHistorial.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPaneHistorial.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneHistorial.setWheelScrollingEnabled(false);

        jPanelHistorial.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHistorial.setPreferredSize(new java.awt.Dimension(988, 1650));
        jPanelHistorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollBarHistorial.setBackground(new java.awt.Color(255, 255, 255));
        jScrollBarHistorial.setMaximum(300);
        jPanelHistorial.add(jScrollBarHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 1650));

        jSeparator25.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator25.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 820, 140, 10));

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(181, 77, 180));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("HISTORIAL CLINICO");
        jPanelHistorial.add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 970, 50));

        jPanelDiseño8.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño8Layout = new javax.swing.GroupLayout(jPanelDiseño8);
        jPanelDiseño8.setLayout(jPanelDiseño8Layout);
        jPanelDiseño8Layout.setHorizontalGroup(
            jPanelDiseño8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelDiseño8Layout.setVerticalGroup(
            jPanelDiseño8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 810, 10));

        jPanelDiseño4.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño4Layout = new javax.swing.GroupLayout(jPanelDiseño4);
        jPanelDiseño4.setLayout(jPanelDiseño4Layout);
        jPanelDiseño4Layout.setHorizontalGroup(
            jPanelDiseño4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelDiseño4Layout.setVerticalGroup(
            jPanelDiseño4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 430, 10));

        jLabelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo3.setText("Datos del Paciente");
        jPanelHistorial.add(jLabelTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 20));

        jLabelTitulo4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo4.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo4.setText("Dirección");
        jLabelTitulo4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelHistorial.add(jLabelTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, 30));

        jPanelDiseño6.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño6Layout = new javax.swing.GroupLayout(jPanelDiseño6);
        jPanelDiseño6.setLayout(jPanelDiseño6Layout);
        jPanelDiseño6Layout.setHorizontalGroup(
            jPanelDiseño6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelDiseño6Layout.setVerticalGroup(
            jPanelDiseño6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 10));

        jPanelDiseño7.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño7Layout = new javax.swing.GroupLayout(jPanelDiseño7);
        jPanelDiseño7.setLayout(jPanelDiseño7Layout);
        jPanelDiseño7Layout.setHorizontalGroup(
            jPanelDiseño7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelDiseño7Layout.setVerticalGroup(
            jPanelDiseño7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabelNomCompPac.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomCompPac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomCompPac.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNomCompPac.setText("Nombre Completo:");
        jPanelHistorial.add(jLabelNomCompPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 30));

        jLabelFolio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFolio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFolio.setForeground(new java.awt.Color(96, 83, 150));
        jLabelFolio.setText("Folio Asignado:");
        jPanelHistorial.add(jLabelFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 30));

        jLabelCurp2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCurp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCurp2.setForeground(new java.awt.Color(96, 83, 150));
        jLabelCurp2.setText("CURP:");
        jPanelHistorial.add(jLabelCurp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 40, 30));

        jLabelFecNac.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFecNac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFecNac.setForeground(new java.awt.Color(96, 83, 150));
        jLabelFecNac.setText("Fecha de Nacimiento:");
        jPanelHistorial.add(jLabelFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 30));

        jLabelTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTelefono.setText("Teléfono:");
        jPanelHistorial.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, 30));

        jLabelReligion.setBackground(new java.awt.Color(255, 255, 255));
        jLabelReligion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelReligion.setForeground(new java.awt.Color(96, 83, 150));
        jLabelReligion.setText("Religión:");
        jPanelHistorial.add(jLabelReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 50, 30));

        jLabelColonia.setBackground(new java.awt.Color(255, 255, 255));
        jLabelColonia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelColonia.setForeground(new java.awt.Color(96, 83, 150));
        jLabelColonia.setText("Colonia:");
        jPanelHistorial.add(jLabelColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 60, 30));

        jLabelMunicipio.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMunicipio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMunicipio.setForeground(new java.awt.Color(96, 83, 150));
        jLabelMunicipio.setText("Municipio:");
        jPanelHistorial.add(jLabelMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 60, 30));

        jLabelNumero.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNumero.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNumero.setText("Número:");
        jPanelHistorial.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, 30));

        jLabelCalle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCalle.setForeground(new java.awt.Color(96, 83, 150));
        jLabelCalle.setText("Calle:");
        jPanelHistorial.add(jLabelCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 60, 30));

        jButtonInsertImg.setBackground(new java.awt.Color(255, 255, 255));
        jButtonInsertImg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonInsertImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        jButtonInsertImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 201, 232)));
        jButtonInsertImg.setContentAreaFilled(false);
        jButtonInsertImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertImgActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jButtonInsertImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 160, 180));

        jLabelTitulo5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo5.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo5.setText("Otros");
        jLabelTitulo5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelHistorial.add(jLabelTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 120, 30));

        jLabelTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTrabajo.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTrabajo.setText("Trabajo:");
        jPanelHistorial.add(jLabelTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 50, 30));

        jLabelEdad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(96, 83, 150));
        jLabelEdad.setText("Edad:");
        jPanelHistorial.add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 30, 30));

        jLabelSexo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(96, 83, 150));
        jLabelSexo.setText("Sexo:");
        jPanelHistorial.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 40, 30));

        jLabelNomComDoc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomComDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNomComDoc.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNomComDoc.setText("Nombre Completo:");
        jPanelHistorial.add(jLabelNomComDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, 110, 30));

        jSeparator6.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator6.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 168, 270, 10));

        jSeparator7.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator7.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 290, 10));

        jSeparator8.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator8.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 340, 10));

        jSeparator9.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator9.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 250, 10));

        jTextFieldTelefonoDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldTelefonoDoc.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldTelefonoDoc.setBorder(null);
        jTextFieldTelefonoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoDocActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldTelefonoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 800, 140, 20));

        jTextFieldNomCompPac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNomCompPac.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldNomCompPac.setBorder(null);
        jTextFieldNomCompPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomCompPacActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldNomCompPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 270, 20));

        jTextFieldFolio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldFolio.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldFolio.setBorder(null);
        jTextFieldFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFolioActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 290, 20));

        jTextCurp2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextCurp2.setForeground(new java.awt.Color(96, 83, 150));
        jTextCurp2.setBorder(null);
        jTextCurp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCurp2ActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextCurp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 340, 20));

        jTextFieldFecNac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldFecNac.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldFecNac.setBorder(null);
        jTextFieldFecNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFecNacActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 250, 20));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(96, 83, 150));
        jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 270, 20));

        jSeparator10.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator10.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 310, 10));

        jSeparator11.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator11.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 240, 10));

        jSeparator12.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator12.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 250, 10));

        jSeparator13.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator13.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 270, 10));

        jSeparator14.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator14.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 250, 10));

        jSeparator15.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator15.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 250, 10));

        jSeparator16.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator16.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 250, 10));

        jSeparator17.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator17.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 270, 10));

        jSeparator18.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator18.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 270, 10));

        jTextFielTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFielTelefono.setForeground(new java.awt.Color(96, 83, 150));
        jTextFielTelefono.setBorder(null);
        jTextFielTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielTelefonoActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFielTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 310, 20));

        jTextFieldMunicipio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldMunicipio.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldMunicipio.setBorder(null);
        jTextFieldMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMunicipioActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 240, 20));

        jTextFieldColonia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldColonia.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldColonia.setBorder(null);
        jTextFieldColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColoniaActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 250, 20));

        jTextFieldCalle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldCalle.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldCalle.setBorder(null);
        jTextFieldCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalleActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 270, 20));

        jTextFieldNumero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNumero.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldNumero.setBorder(null);
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 250, 20));

        jTextFieldReligion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldReligion.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldReligion.setBorder(null);
        jTextFieldReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldReligionActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 250, 20));

        jTextFieldTrabajo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldTrabajo.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldTrabajo.setBorder(null);
        jTextFieldTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTrabajoActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 250, 20));

        jTextFieldEdad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldEdad.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldEdad.setBorder(null);
        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 270, 20));

        jTextFieldSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldSexo.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldSexo.setBorder(null);
        jTextFieldSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexoActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 270, 20));

        jPanelDiseño5.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño5Layout = new javax.swing.GroupLayout(jPanelDiseño5);
        jPanelDiseño5.setLayout(jPanelDiseño5Layout);
        jPanelDiseño5Layout.setHorizontalGroup(
            jPanelDiseño5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanelDiseño5Layout.setVerticalGroup(
            jPanelDiseño5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 430, 10));

        jLabelTitulo6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo6.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo6.setText("Datos del Medico");
        jPanelHistorial.add(jLabelTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 160, 20));

        jPanelDiseño9.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño9Layout = new javax.swing.GroupLayout(jPanelDiseño9);
        jPanelDiseño9.setLayout(jPanelDiseño9Layout);
        jPanelDiseño9Layout.setHorizontalGroup(
            jPanelDiseño9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelDiseño9Layout.setVerticalGroup(
            jPanelDiseño9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 160, 10));

        jPanelDiseño10.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño10Layout = new javax.swing.GroupLayout(jPanelDiseño10);
        jPanelDiseño10.setLayout(jPanelDiseño10Layout);
        jPanelDiseño10Layout.setHorizontalGroup(
            jPanelDiseño10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelDiseño10Layout.setVerticalGroup(
            jPanelDiseño10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, -1, -1));

        jComboBoxDoctores.setBackground(new java.awt.Color(96, 83, 150));
        jComboBoxDoctores.setEditable(true);
        jComboBoxDoctores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxDoctores.setForeground(new java.awt.Color(96, 83, 150));
        jComboBoxDoctores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDoctores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxDoctores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxDoctores.setFocusCycleRoot(true);
        jPanelHistorial.add(jComboBoxDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 300, -1));

        jLabelTipSangre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTipSangre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTipSangre.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTipSangre.setText("Tipo de Sangre:");
        jPanelHistorial.add(jLabelTipSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 90, 30));

        jLabelCedulaProfesional.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCedulaProfesional.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCedulaProfesional.setForeground(new java.awt.Color(96, 83, 150));
        jLabelCedulaProfesional.setText("Cédula Profesional:");
        jPanelHistorial.add(jLabelCedulaProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 110, 30));

        jLabelDireccionDoc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDireccionDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDireccionDoc.setForeground(new java.awt.Color(96, 83, 150));
        jLabelDireccionDoc.setText("Dirección:");
        jPanelHistorial.add(jLabelDireccionDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 810, 60, 30));

        jLabelTitulo8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo8.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo8.setText("Descripción de los Antecedentes del Paciente");
        jPanelHistorial.add(jLabelTitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 960, 970, 30));

        jLabelEdadDoc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEdadDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEdadDoc.setForeground(new java.awt.Color(96, 83, 150));
        jLabelEdadDoc.setText("Edad:");
        jPanelHistorial.add(jLabelEdadDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 730, 30, 30));

        jLabelSexoDoc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSexoDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSexoDoc.setForeground(new java.awt.Color(96, 83, 150));
        jLabelSexoDoc.setText("Sexo:");
        jPanelHistorial.add(jLabelSexoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 760, 40, 30));

        jSeparator19.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator19.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 210, 10));

        jSeparator20.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator20.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 750, 240, 10));

        jSeparator21.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator21.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 790, 240, 10));

        jSeparator22.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator22.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 830, 290, 10));

        jSeparator23.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator23.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 750, 160, 10));

        jSeparator24.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator24.setForeground(new java.awt.Color(232, 201, 232));
        jPanelHistorial.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 780, 160, 10));

        jTextFieldTipSangre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldTipSangre.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldTipSangre.setBorder(null);
        jTextFieldTipSangre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipSangreActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldTipSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 210, 20));

        jPanelDiseño11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño11Layout = new javax.swing.GroupLayout(jPanelDiseño11);
        jPanelDiseño11.setLayout(jPanelDiseño11Layout);
        jPanelDiseño11Layout.setHorizontalGroup(
            jPanelDiseño11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanelDiseño11Layout.setVerticalGroup(
            jPanelDiseño11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 880, -1, 10));

        jLabelTitulo7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo7.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo7.setText("Datos Clínicos");
        jPanelHistorial.add(jLabelTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 910, 160, 20));

        jPanelDiseño12.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño12Layout = new javax.swing.GroupLayout(jPanelDiseño12);
        jPanelDiseño12.setLayout(jPanelDiseño12Layout);
        jPanelDiseño12Layout.setHorizontalGroup(
            jPanelDiseño12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelDiseño12Layout.setVerticalGroup(
            jPanelDiseño12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 900, 160, 10));

        jPanelDiseño13.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanelDiseño13Layout = new javax.swing.GroupLayout(jPanelDiseño13);
        jPanelDiseño13.setLayout(jPanelDiseño13Layout);
        jPanelDiseño13Layout.setHorizontalGroup(
            jPanelDiseño13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanelDiseño13Layout.setVerticalGroup(
            jPanelDiseño13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanelHistorial.add(jPanelDiseño13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 930, -1, -1));

        jLabelTitulo12.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo12.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo12.setText("Antecedentes  Quirurgicos:");
        jPanelHistorial.add(jLabelTitulo12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1250, 170, 30));

        jLabelTelefonoDoc.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTelefonoDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTelefonoDoc.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTelefonoDoc.setText("Teléfono:");
        jPanelHistorial.add(jLabelTelefonoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 800, 60, 30));

        jLabelTitulo10.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo10.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo10.setText("Antecedentes Heredo-Familiares");
        jPanelHistorial.add(jLabelTitulo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1020, 200, 20));

        jLabelTitulo9.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo9.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo9.setText("Antecedentes Personales:");
        jPanelHistorial.add(jLabelTitulo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1010, 150, 30));

        jLabelTitulo11.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo11.setForeground(new java.awt.Color(96, 83, 150));
        jLabelTitulo11.setText("Antecedentes Patologicos");
        jPanelHistorial.add(jLabelTitulo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1260, 150, 30));

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setEnabled(false);
        jScrollPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jScrollPane2KeyReleased(evt);
            }
        });

        jPanel18.setEnabled(false);

        jTextAreaAntPer.setColumns(20);
        jTextAreaAntPer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextAreaAntPer.setForeground(new java.awt.Color(96, 83, 150));
        jTextAreaAntPer.setLineWrap(true);
        jTextAreaAntPer.setRows(5);
        jTextAreaAntPer.setText("Escribir Aquí...");
        jTextAreaAntPer.setEnabled(false);
        jTextAreaAntPer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaAntPerKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaAntPerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaAntPerKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(jTextAreaAntPer);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel18);

        jPanelHistorial.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1040, 400, 180));

        jScrollPane3.setEnabled(false);

        jPanel19.setEnabled(false);

        jTextAreaAntFam.setColumns(20);
        jTextAreaAntFam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextAreaAntFam.setForeground(new java.awt.Color(96, 83, 150));
        jTextAreaAntFam.setLineWrap(true);
        jTextAreaAntFam.setRows(5);
        jTextAreaAntFam.setText("Escribir Aquí...");
        jTextAreaAntFam.setEnabled(false);
        jTextAreaAntFam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaAntFamKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaAntFamKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(jTextAreaAntFam);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel19);

        jPanelHistorial.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1040, 430, 180));

        jScrollPane4.setEnabled(false);

        jPanel20.setEnabled(false);

        jTextAreaAntPat.setColumns(20);
        jTextAreaAntPat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextAreaAntPat.setForeground(new java.awt.Color(96, 83, 150));
        jTextAreaAntPat.setLineWrap(true);
        jTextAreaAntPat.setRows(5);
        jTextAreaAntPat.setText("Escribir Aquí...");
        jTextAreaAntPat.setEnabled(false);
        jTextAreaAntPat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaAntPatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaAntPatKeyTyped(evt);
            }
        });
        jScrollPane8.setViewportView(jTextAreaAntPat);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel20);

        jPanelHistorial.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1290, 400, 180));

        jScrollPane5.setEnabled(false);

        jTextAreaAntQuir.setColumns(20);
        jTextAreaAntQuir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextAreaAntQuir.setForeground(new java.awt.Color(96, 83, 150));
        jTextAreaAntQuir.setLineWrap(true);
        jTextAreaAntQuir.setRows(5);
        jTextAreaAntQuir.setText("Escribir Aquí...");
        jTextAreaAntQuir.setEnabled(false);
        jTextAreaAntQuir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaAntQuirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaAntQuirKeyTyped(evt);
            }
        });
        jScrollPane9.setViewportView(jTextAreaAntQuir);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel21);

        jPanelHistorial.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 1280, 430, 180));

        jButtonModificar.setBackground(new java.awt.Color(232, 201, 232));
        jButtonModificar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(96, 83, 150));
        jButtonModificar.setText("Modificar");
        jButtonModificar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonModificar.setBorderPainted(false);
        jButtonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1550, 160, 40));

        jButtonGuardar.setBackground(new java.awt.Color(232, 201, 232));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(96, 83, 150));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonGuardar.setBorderPainted(false);
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1550, 160, 40));

        jTextFieldNomComDoc1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldNomComDoc1.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldNomComDoc1.setBorder(null);
        jTextFieldNomComDoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomComDoc1ActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldNomComDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 730, 240, 20));

        jTextFieldCedulaProfesional.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldCedulaProfesional.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldCedulaProfesional.setBorder(null);
        jTextFieldCedulaProfesional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaProfesionalActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldCedulaProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 770, 240, 20));

        jTextFieldDireccionDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldDireccionDoc.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldDireccionDoc.setBorder(null);
        jTextFieldDireccionDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionDocActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldDireccionDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 810, 290, 20));

        jTextFieldEdadDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldEdadDoc.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldEdadDoc.setBorder(null);
        jTextFieldEdadDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadDocActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldEdadDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 730, 160, 20));

        jTextFieldSexoDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldSexoDoc.setForeground(new java.awt.Color(96, 83, 150));
        jTextFieldSexoDoc.setBorder(null);
        jTextFieldSexoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSexoDocActionPerformed(evt);
            }
        });
        jPanelHistorial.add(jTextFieldSexoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 760, 160, 20));

        jScrollPaneHistorial.setViewportView(jPanelHistorial);

        jPanelGeneral.add(jScrollPaneHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 730));

        getContentPane().add(jPanelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEsconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsconderActionPerformed
        // TODO add your handling code here:
                int posicion = jPanelPerfil.getX();
        if(posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -318, 2, 2, jPanelPerfil);
            //Animacion.Animacion.mover_izquierda()
        }else{
            Animacion.Animacion.mover_derecha(-318, 0, 2, 2, jPanelPerfil);
        }
    }//GEN-LAST:event_jButtonEsconderActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldAPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAPaternoActionPerformed

    private void jTextFieldAMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAMaternoActionPerformed

    private void jTextFieldCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCurpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCurpActionPerformed

    private void jTextFieldTipSangreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipSangreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipSangreActionPerformed

    private void jTextFieldSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSexoActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jTextFieldTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTrabajoActionPerformed

    private void jTextFieldReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldReligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReligionActionPerformed

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jTextFieldCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalleActionPerformed

    private void jTextFieldColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColoniaActionPerformed

    private void jTextFieldMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMunicipioActionPerformed

    private void jTextFielTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielTelefonoActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextFieldFecNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFecNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFecNacActionPerformed

    private void jTextCurp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCurp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCurp2ActionPerformed

    private void jTextFieldFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFolioActionPerformed

    private void jTextFieldNomCompPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomCompPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomCompPacActionPerformed

    private void jTextFieldTelefonoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoDocActionPerformed

    private void jButtonInsertImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInsertImgActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jTextFieldNomComDoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomComDoc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomComDoc1ActionPerformed

    private void jTextFieldCedulaProfesionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaProfesionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaProfesionalActionPerformed

    private void jTextFieldDireccionDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionDocActionPerformed

    private void jTextFieldEdadDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadDocActionPerformed

    private void jTextFieldSexoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSexoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSexoDocActionPerformed

    private void jButtonregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonregresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonregresarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        JTextArea ventana1 = jTextAreaAntPer;
        JTextArea ventana2 = jTextAreaAntFam;
        JTextArea ventana3 = jTextAreaAntPat;
        JTextArea ventana4 = jTextAreaAntQuir;
        //Se desactivan las ventanas para su modificacion
        ventana1.enable(true);
        ventana2.enable(true);
        ventana3.enable(true);
        ventana4.enable(true);
    
    }//GEN-LAST:event_jButtonModificarActionPerformed
//Hacer lo mismo con todos los datos>
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
JTextArea ventana1 = jTextAreaAntPer;
        JTextArea ventana2 = jTextAreaAntFam;
        JTextArea ventana3 = jTextAreaAntPat;
        JTextArea ventana4 = jTextAreaAntQuir;
        //Agregar una validaciòn de SQL que evite que el administrador pueda meter comandos SQL desde el textarea (En los 4), permite cadenas en general
        //Se desactivan als ventanas una vez guardado
        ventana1.disable();
        ventana2.disable();
        ventana3.disable();
        ventana4.disable();
            //Se limpian las ventanas para posteriormente verificar la informaciòn en BD
        ventana1.setText("");
        ventana2.setText("");
        ventana3.setText("");
        ventana4.setText("");
        //Se jala a la base de datos para verificar la informaciòn en BD
     //No se como hacerlo :(

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jScrollPane2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jScrollPane2KeyReleased

    }//GEN-LAST:event_jScrollPane2KeyReleased

    private void jTextAreaAntPerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntPerKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntPerKeyPressed

    private void jTextAreaAntPerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntPerKeyReleased
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntPerKeyReleased

    private void jTextAreaAntFamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntFamKeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntFamKeyReleased

    private void jTextAreaAntPatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntPatKeyReleased
       // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntPatKeyReleased

    private void jTextAreaAntQuirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntQuirKeyReleased
     // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntQuirKeyReleased

    private void jTextAreaAntPerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntPerKeyTyped
Validaciones.validaAlfanumerico(evt);   
if (jTextAreaAntPer.getText().length() == 255)
        {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntPerKeyTyped

    private void jTextAreaAntFamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntFamKeyTyped
Validaciones.validaAlfanumerico(evt); 
if (jTextAreaAntFam.getText().length() == 255)
        {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntFamKeyTyped

    private void jTextAreaAntPatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntPatKeyTyped
Validaciones.validaAlfanumerico(evt);  
if (jTextAreaAntPat.getText().length() == 255)
        {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntPatKeyTyped

    private void jTextAreaAntQuirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaAntQuirKeyTyped
Validaciones.validaAlfanumerico(evt);     
if (jTextAreaAntQuir.getText().length() == 255)
        {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAntQuirKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 con = ManipulaDBC.conectaDB();
        evitarPegar(jTextFieldNombre, jTextFieldAMaterno, jTextFieldAPaterno, jTextFieldCurp);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 ManipulaDBC.desconectaDB(con);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void evitarPegar(Object... objs) {
        for (Object obj : objs)
        {
            if (obj instanceof JTextField)
            {
                InputMap map2 = ((JTextField) obj).getInputMap(JTextField.WHEN_FOCUSED);
                map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
            }
        }
    }
    public static void connect()
{
String url = "jdbc:mysql://localhost:3306/myjavaapp1";
String user = "root";
String pass = "123456";
System.out.println("Conectando…");
try(Connection connection = DriverManager.getConnection(url, user,pass))
{
System.out.println("Conectado!!");
}
catch(SQLException e)
{
System.out.println(e.getMessage());
}
}

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        connect();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonEsconder;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonInsertImg;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtoncerrar;
    private javax.swing.JButton jButtonminimizar;
    private javax.swing.JButton jButtonregresar;
    private javax.swing.JComboBox<String> jComboBoxDoctores;
    private javax.swing.JLabel jLabelAMaterno;
    private javax.swing.JLabel jLabelAPaterno;
    private javax.swing.JLabel jLabelCalle;
    private javax.swing.JLabel jLabelCedulaProfesional;
    private javax.swing.JLabel jLabelColonia;
    private javax.swing.JLabel jLabelCurp;
    private javax.swing.JLabel jLabelCurp2;
    private javax.swing.JLabel jLabelDireccionDoc;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdadDoc;
    private javax.swing.JLabel jLabelFecNac;
    private javax.swing.JLabel jLabelFolio;
    private javax.swing.JLabel jLabelFotoPefil;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNomComDoc;
    private javax.swing.JLabel jLabelNomCompPac;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelReligion;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSexoDoc;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoDoc;
    private javax.swing.JLabel jLabelTipSangre;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo10;
    private javax.swing.JLabel jLabelTitulo11;
    private javax.swing.JLabel jLabelTitulo12;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelTitulo4;
    private javax.swing.JLabel jLabelTitulo5;
    private javax.swing.JLabel jLabelTitulo6;
    private javax.swing.JLabel jLabelTitulo7;
    private javax.swing.JLabel jLabelTitulo8;
    private javax.swing.JLabel jLabelTitulo9;
    private javax.swing.JLabel jLabelTrabajo;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanelDiseño1;
    private javax.swing.JPanel jPanelDiseño10;
    private javax.swing.JPanel jPanelDiseño11;
    private javax.swing.JPanel jPanelDiseño12;
    private javax.swing.JPanel jPanelDiseño13;
    private javax.swing.JPanel jPanelDiseño2;
    private javax.swing.JPanel jPanelDiseño3;
    private javax.swing.JPanel jPanelDiseño4;
    private javax.swing.JPanel jPanelDiseño5;
    private javax.swing.JPanel jPanelDiseño6;
    private javax.swing.JPanel jPanelDiseño7;
    private javax.swing.JPanel jPanelDiseño8;
    private javax.swing.JPanel jPanelDiseño9;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelHistorial;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JScrollBar jScrollBarHistorial;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPaneHistorial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextAreaAntFam;
    private javax.swing.JTextArea jTextAreaAntPat;
    private javax.swing.JTextArea jTextAreaAntPer;
    private javax.swing.JTextArea jTextAreaAntQuir;
    private javax.swing.JTextField jTextCurp2;
    private javax.swing.JTextField jTextFielTelefono;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextFieldAMaterno;
    private javax.swing.JTextField jTextFieldAPaterno;
    private javax.swing.JTextField jTextFieldCalle;
    private javax.swing.JTextField jTextFieldCedulaProfesional;
    private javax.swing.JTextField jTextFieldColonia;
    private javax.swing.JTextField jTextFieldCurp;
    private javax.swing.JTextField jTextFieldDireccionDoc;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldEdadDoc;
    private javax.swing.JTextField jTextFieldFecNac;
    private javax.swing.JTextField jTextFieldFolio;
    private javax.swing.JTextField jTextFieldMunicipio;
    private javax.swing.JTextField jTextFieldNomComDoc1;
    private javax.swing.JTextField jTextFieldNomCompPac;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldReligion;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextFieldSexoDoc;
    private javax.swing.JTextField jTextFieldTelefonoDoc;
    private javax.swing.JTextField jTextFieldTipSangre;
    private javax.swing.JTextField jTextFieldTrabajo;
    // End of variables declaration//GEN-END:variables
}
