/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agregar_m;

import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class AM extends javax.swing.JFrame {

    /**
     * Creates new form AM
     */
    public AM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelDiseño3 = new javax.swing.JPanel();
        jButtoncerrar = new javax.swing.JButton();
        jButtoncerrar1 = new javax.swing.JButton();
        jButtonminimizar2 = new javax.swing.JButton();
        jButtoncerrar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelAPaterno = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jButtonConsultar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabelTitulo3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtUsuario1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtUsuario2 = new javax.swing.JTextField();
        txtUsuario3 = new javax.swing.JTextField();
        jLabelAPaterno1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelAPaterno2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtUsuario4 = new javax.swing.JTextField();
        jLabelAPaterno3 = new javax.swing.JLabel();
        jLabelAPaterno4 = new javax.swing.JLabel();
        txtUsuario5 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtUsuario6 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabelAPaterno5 = new javax.swing.JLabel();
        jLabelAPaterno6 = new javax.swing.JLabel();
        jLabelAPaterno7 = new javax.swing.JLabel();
        txtUsuario7 = new javax.swing.JTextField();
        txtUsuario8 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txtUsuario9 = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtUsuario10 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabelAPaterno8 = new javax.swing.JLabel();
        jLabelAPaterno9 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        txtUsuario11 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        txtUsuario12 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDiseño3.setBackground(new java.awt.Color(96, 83, 150));

        jButtoncerrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncerrar.setBorder(null);
        jButtoncerrar.setBorderPainted(false);
        jButtoncerrar.setContentAreaFilled(false);
        jButtoncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtoncerrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jButtoncerrar1.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncerrar1.setBorder(null);
        jButtoncerrar1.setBorderPainted(false);
        jButtoncerrar1.setContentAreaFilled(false);
        jButtoncerrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtoncerrar1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtoncerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncerrar1ActionPerformed(evt);
            }
        });

        jButtonminimizar2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonminimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jButtonminimizar2.setBorderPainted(false);
        jButtonminimizar2.setContentAreaFilled(false);
        jButtonminimizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonminimizar2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jButtoncerrar2.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncerrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtoncerrar2.setBorder(null);
        jButtoncerrar2.setBorderPainted(false);
        jButtoncerrar2.setContentAreaFilled(false);
        jButtoncerrar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtoncerrar2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout jPanelDiseño3Layout = new javax.swing.GroupLayout(jPanelDiseño3);
        jPanelDiseño3.setLayout(jPanelDiseño3Layout);
        jPanelDiseño3Layout.setHorizontalGroup(
            jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiseño3Layout.createSequentialGroup()
                .addGroup(jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDiseño3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtoncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButtoncerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDiseño3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonminimizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtoncerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanelDiseño3Layout.setVerticalGroup(
            jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiseño3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtoncerrar2)
                    .addComponent(jButtonminimizar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(801, 801, 801)
                .addGroup(jPanelDiseño3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtoncerrar1)
                    .addComponent(jButtoncerrar)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 83, 150)));

        btnEntrar.setBackground(new java.awt.Color(232, 201, 232));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(96, 83, 150));
        btnEntrar.setText("Validar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario.setBorder(null);

        jLabelNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre.setText("Apellido Paterno");

        jLabelAPaterno.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno.setText("Curp:");

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(181, 77, 180));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Agregar Medico:");

        jButtonConsultar1.setBackground(new java.awt.Color(232, 201, 232));
        jButtonConsultar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonConsultar1.setForeground(new java.awt.Color(96, 83, 150));
        jButtonConsultar1.setText("Agregar");
        jButtonConsultar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonConsultar1.setBorderPainted(false);
        jButtonConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConsultar1.setFocusPainted(false);
        jButtonConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultar1ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator2.setForeground(new java.awt.Color(232, 201, 232));

        jSeparator3.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator3.setForeground(new java.awt.Color(232, 201, 232));

        jLabelNombre1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre1.setText("Apellido Materno");

        jLabelNombre2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre2.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre2.setText("Nombre");

        jLabelTitulo3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(181, 77, 180));
        jLabelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo3.setText("Verificacion de cedula:");

        jSeparator4.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator4.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario1.setBorder(null);

        jSeparator5.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator5.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario2.setBorder(null);

        txtUsuario3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario3.setBorder(null);

        jLabelAPaterno1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno1.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno1.setText("Cedula:");

        jSeparator6.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator6.setForeground(new java.awt.Color(232, 201, 232));

        jLabelAPaterno2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno2.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno2.setText("Correo:");

        jSeparator7.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator7.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario4.setBorder(null);

        jLabelAPaterno3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno3.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno3.setText("Contraseña:");

        jLabelAPaterno4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno4.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno4.setText("Verificacion contraseña:");

        txtUsuario5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario5.setBorder(null);

        jSeparator8.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator8.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario6.setBorder(null);

        jSeparator9.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator9.setForeground(new java.awt.Color(232, 201, 232));

        jLabelAPaterno5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno5.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno5.setText("Telefono:");

        jLabelAPaterno6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno6.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno6.setText("Fecha de nacimiento:");

        jLabelAPaterno7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno7.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno7.setText("Sexo:");

        txtUsuario7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario7.setBorder(null);

        txtUsuario8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario8.setBorder(null);

        jSeparator10.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator10.setForeground(new java.awt.Color(232, 201, 232));

        jSeparator11.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator11.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario9.setBorder(null);

        jSeparator12.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator12.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario10.setBorder(null);

        jSeparator13.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator13.setForeground(new java.awt.Color(232, 201, 232));

        jLabelAPaterno8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno8.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno8.setText("RFC:");

        jLabelAPaterno9.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAPaterno9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelAPaterno9.setForeground(new java.awt.Color(96, 83, 150));
        jLabelAPaterno9.setText("Especialidad:");

        jSeparator14.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator14.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario11.setBorder(null);

        jSeparator15.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator15.setForeground(new java.awt.Color(232, 201, 232));

        txtUsuario12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUsuario12.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jSeparator4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNombre1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(336, 336, 336))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelAPaterno3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator8)
                                        .addComponent(txtUsuario5)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelAPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator7)
                                        .addComponent(txtUsuario4)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelAPaterno5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator10)
                                        .addComponent(txtUsuario7)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelAPaterno4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabelAPaterno6)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(184, 184, 184)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator11)
                                        .addComponent(txtUsuario8)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabelAPaterno8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtUsuario10, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabelAPaterno7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(4, 4, 4)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabelAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtUsuario11, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(281, 281, 281)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelAPaterno9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario12, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jButtonConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAPaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAPaterno2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAPaterno3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAPaterno4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuario7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAPaterno5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAPaterno6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAPaterno7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelAPaterno9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txtUsuario11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtUsuario10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelAPaterno8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(txtUsuario12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(jButtonConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDiseño3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelDiseño3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncerrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncerrar1ActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        SqlUsuarios modSql = new SqlUsuarios();
        Usuarios mod = new Usuarios();
        String pass = new String(txtPassword.getPassword());

        if (!txtUsuario.getText().equals("") && !pass.equals("")) {

            String nuevoPass = Hash.sha1(pass);

            mod.setUsuario(txtUsuario.getText());
            mod.setPassword(nuevoPass);

            if (modSql.login(mod)) {
                Inicio.frmLog = null;
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
                //limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
      }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButtonConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEntrar;
    private javax.swing.JButton jButtonConsultar1;
    private javax.swing.JButton jButtoncerrar;
    private javax.swing.JButton jButtoncerrar1;
    private javax.swing.JButton jButtoncerrar2;
    private javax.swing.JButton jButtonminimizar2;
    private javax.swing.JLabel jLabelAPaterno;
    private javax.swing.JLabel jLabelAPaterno1;
    private javax.swing.JLabel jLabelAPaterno2;
    private javax.swing.JLabel jLabelAPaterno3;
    private javax.swing.JLabel jLabelAPaterno4;
    private javax.swing.JLabel jLabelAPaterno5;
    private javax.swing.JLabel jLabelAPaterno6;
    private javax.swing.JLabel jLabelAPaterno7;
    private javax.swing.JLabel jLabelAPaterno8;
    private javax.swing.JLabel jLabelAPaterno9;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDiseño3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField txtUsuario;
    public javax.swing.JTextField txtUsuario1;
    public javax.swing.JTextField txtUsuario10;
    public javax.swing.JTextField txtUsuario11;
    public javax.swing.JTextField txtUsuario12;
    public javax.swing.JTextField txtUsuario2;
    public javax.swing.JTextField txtUsuario3;
    public javax.swing.JTextField txtUsuario4;
    public javax.swing.JTextField txtUsuario5;
    public javax.swing.JTextField txtUsuario6;
    public javax.swing.JTextField txtUsuario7;
    public javax.swing.JTextField txtUsuario8;
    public javax.swing.JTextField txtUsuario9;
    // End of variables declaration//GEN-END:variables

    private static class SqlUsuarios {

        public SqlUsuarios() {
        }

        private boolean login(Usuarios mod) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class Usuarios {

        public Usuarios() {
        }

        private void setUsuario(String text) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private void setPassword(String nuevoPass) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class txtPassword {

        private static String getPassword() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txtPassword() {
        }
    }

    private static class Hash {

        private static String sha1(String pass) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Hash() {
        }
    }

    private static class Inicio {

        private static Object frmLog;

        public Inicio() {
        }
    }
}
