/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agregar_m;

import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class AM extends javax.swing.JFrame {

    /**
     * Creates new form AM
     */
    public AM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        panelprincipal = new javax.swing.JPanel();
        paneldatospersonales = new javax.swing.JPanel();
        jLabelNombre4 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelNombre6 = new javax.swing.JLabel();
        jtfnombre4 = new javax.swing.JTextField();
        jLabelNombre5 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabelNombre7 = new javax.swing.JLabel();
        jtfnombre6 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jtfnombre5 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jtfnombre7 = new javax.swing.JTextField();
        jLabelNombre8 = new javax.swing.JLabel();
        jltitulovalidar1 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jtfnombre8 = new javax.swing.JTextField();
        jLabelNombre9 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jtfnombre9 = new javax.swing.JTextField();
        jLabelNombre10 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jtfnombre10 = new javax.swing.JTextField();
        jLabelNombre11 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jtfnombre11 = new javax.swing.JTextField();
        jLabelNombre12 = new javax.swing.JLabel();
        jbsalir = new javax.swing.JButton();
        jbaceptar1 = new javax.swing.JButton();
        panelverificar = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabelNombre1 = new javax.swing.JLabel();
        jtfprimerape1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabelNombre = new javax.swing.JLabel();
        jtfprimerape = new javax.swing.JTextField();
        jltitulovalidar = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jtfnombre = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();
        jBConsultar = new javax.swing.JButton();
        jLabelNombre3 = new javax.swing.JLabel();
        jlmensajeerror = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jtfnombre1 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jtfnombre2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jtfnombre3 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jtfcedula = new javax.swing.JTextField();
        panelbarrasuperior = new javax.swing.JPanel();
        jButtonminimizar = new javax.swing.JButton();
        jButtoncerrar = new javax.swing.JButton();
        jButtonregresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprincipal.setPreferredSize(new java.awt.Dimension(960, 980));

        paneldatospersonales.setBackground(new java.awt.Color(255, 255, 255));
        paneldatospersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 255))); // NOI18N
        paneldatospersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre4.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre4.setText("Sexo:");
        paneldatospersonales.add(jLabelNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jSeparator11.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator11.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 116, 200, 10));

        jSeparator10.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator10.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 116, 200, 10));

        jLabelNombre6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre6.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre6.setText("Telefono:");
        paneldatospersonales.add(jLabelNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jtfnombre4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre4.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre4.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre4.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, 26));

        jLabelNombre5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre5.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre5.setText("Fecha de nacimiento:");
        paneldatospersonales.add(jLabelNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jSeparator13.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator13.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 176, 200, 10));

        jSeparator12.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator12.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 176, 200, 10));

        jLabelNombre7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre7.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre7.setText("CURP:");
        paneldatospersonales.add(jLabelNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jtfnombre6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre6.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre6.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre6.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 200, 26));
        paneldatospersonales.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 200, 26));

        jtfnombre5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre5.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre5.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre5.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 26));

        jSeparator14.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator14.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 236, 200, 10));

        jtfnombre7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre7.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre7.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre7.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 200, 26));

        jLabelNombre8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre8.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre8.setText("RFC:");
        paneldatospersonales.add(jLabelNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 213, -1, 20));

        jltitulovalidar1.setBackground(new java.awt.Color(255, 255, 255));
        jltitulovalidar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jltitulovalidar1.setForeground(new java.awt.Color(181, 77, 180));
        jltitulovalidar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulovalidar1.setText("Información Personal:");
        paneldatospersonales.add(jltitulovalidar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 40));

        jSeparator15.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator15.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 236, 200, 10));

        jtfnombre8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre8.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre8.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre8.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 200, 26));

        jLabelNombre9.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre9.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre9.setText("Especialidad:");
        paneldatospersonales.add(jLabelNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jSeparator18.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator18.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 296, 200, 10));

        jtfnombre9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre9.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre9.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre9.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 200, 26));

        jLabelNombre10.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre10.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre10.setText("Correo:");
        paneldatospersonales.add(jLabelNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jSeparator19.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator19.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 356, 200, 10));

        jtfnombre10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre10.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre10.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre10.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 200, 26));

        jLabelNombre11.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre11.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre11.setText("Contraseña:");
        paneldatospersonales.add(jLabelNombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jSeparator20.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator20.setForeground(new java.awt.Color(232, 201, 232));
        paneldatospersonales.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 356, 200, 10));

        jtfnombre11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre11.setForeground(new java.awt.Color(96, 83, 150));
        jtfnombre11.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre11.setMinimumSize(new java.awt.Dimension(48, 26));
        paneldatospersonales.add(jtfnombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 200, 26));

        jLabelNombre12.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre12.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre12.setText("Repetir contraseña: ");
        paneldatospersonales.add(jLabelNombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, -1, -1));

        jbsalir.setBackground(new java.awt.Color(232, 201, 232));
        jbsalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbsalir.setForeground(new java.awt.Color(96, 83, 150));
        jbsalir.setText("Salir");
        jbsalir.setBorderPainted(false);
        jbsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbsalir.setFocusPainted(false);
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });
        paneldatospersonales.add(jbsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 140, -1));

        jbaceptar1.setBackground(new java.awt.Color(232, 201, 232));
        jbaceptar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbaceptar1.setForeground(new java.awt.Color(96, 83, 150));
        jbaceptar1.setText("Agregar");
        jbaceptar1.setBorderPainted(false);
        jbaceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbaceptar1.setFocusPainted(false);
        jbaceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaceptar1ActionPerformed(evt);
            }
        });
        paneldatospersonales.add(jbaceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 140, -1));

        panelverificar.setBackground(new java.awt.Color(255, 255, 255));
        panelverificar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(232, 201, 232))); // NOI18N
        panelverificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator17.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator17.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 250, 10));

        jLabelNombre1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre1.setText("Segundo apellido*");
        panelverificar.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        jtfprimerape1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfprimerape1.setForeground(new java.awt.Color(102, 102, 102));
        jtfprimerape1.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfprimerape1.setMinimumSize(new java.awt.Dimension(48, 26));
        jtfprimerape1.setPreferredSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfprimerape1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 114, 250, 26));

        jSeparator16.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator16.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 140, 250, 10));

        jLabelNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre.setText("Primer apellido*");
        panelverificar.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 140, -1));

        jtfprimerape.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfprimerape.setForeground(new java.awt.Color(102, 102, 102));
        jtfprimerape.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfprimerape.setMinimumSize(new java.awt.Dimension(48, 26));
        jtfprimerape.setPreferredSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfprimerape, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 114, 250, 26));

        jltitulovalidar.setBackground(new java.awt.Color(255, 255, 255));
        jltitulovalidar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jltitulovalidar.setForeground(new java.awt.Color(181, 77, 180));
        jltitulovalidar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltitulovalidar.setText("Verificacion de cedula:");
        panelverificar.add(jltitulovalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 40));

        jLabelTitulo2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(181, 77, 180));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Agregar Medico:");
        panelverificar.add(jLabelTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, 40));

        jtfnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre.setForeground(new java.awt.Color(102, 102, 102));
        jtfnombre.setText("Carlos");
        jtfnombre.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre.setMinimumSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 114, 250, 26));

        jLabelNombre2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre2.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre2.setText("Número de Cedula");
        panelverificar.add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jBConsultar.setBackground(new java.awt.Color(232, 201, 232));
        jBConsultar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBConsultar.setForeground(new java.awt.Color(96, 83, 150));
        jBConsultar.setText("Consultar");
        jBConsultar.setBorderPainted(false);
        jBConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBConsultar.setFocusPainted(false);
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        panelverificar.add(jBConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 140, -1));

        jLabelNombre3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelNombre3.setForeground(new java.awt.Color(96, 83, 150));
        jLabelNombre3.setText("Nombre(s)*");
        panelverificar.add(jLabelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jlmensajeerror.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlmensajeerror.setForeground(new java.awt.Color(218, 2, 2));
        jlmensajeerror.setText("Cedula inexistente");
        panelverificar.add(jlmensajeerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 150, 20));

        jSeparator5.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator5.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 10));

        jSeparator6.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator6.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 10));

        jtfnombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre1.setForeground(new java.awt.Color(102, 102, 102));
        jtfnombre1.setText("Carlos");
        jtfnombre1.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre1.setMinimumSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 114, 250, 26));

        jSeparator7.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator7.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 10));

        jtfnombre2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre2.setForeground(new java.awt.Color(102, 102, 102));
        jtfnombre2.setText("Carlos");
        jtfnombre2.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre2.setMinimumSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfnombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 114, 250, 26));

        jSeparator8.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator8.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 10));

        jtfnombre3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfnombre3.setForeground(new java.awt.Color(102, 102, 102));
        jtfnombre3.setText("Carlos");
        jtfnombre3.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfnombre3.setMinimumSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfnombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 114, 250, 26));

        jSeparator9.setBackground(new java.awt.Color(232, 201, 232));
        jSeparator9.setForeground(new java.awt.Color(232, 201, 232));
        panelverificar.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 306, 250, 10));

        jtfcedula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfcedula.setForeground(new java.awt.Color(102, 102, 102));
        jtfcedula.setMaximumSize(new java.awt.Dimension(48, 26));
        jtfcedula.setMinimumSize(new java.awt.Dimension(48, 26));
        panelverificar.add(jtfcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 280, 250, 26));

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paneldatospersonales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelverificar, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                .addComponent(panelverificar, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paneldatospersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setViewportView(panelprincipal);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 980, 650));

        panelbarrasuperior.setBackground(new java.awt.Color(96, 83, 150));
        panelbarrasuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonminimizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jButtonminimizar.setBorderPainted(false);
        jButtonminimizar.setContentAreaFilled(false);
        jButtonminimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonminimizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtonminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonminimizarMouseClicked(evt);
            }
        });
        panelbarrasuperior.add(jButtonminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 10, 34, 33));

        jButtoncerrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtoncerrar.setBorder(null);
        jButtoncerrar.setBorderPainted(false);
        jButtoncerrar.setContentAreaFilled(false);
        jButtoncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtoncerrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButtoncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoncerrarMouseClicked(evt);
            }
        });
        panelbarrasuperior.add(jButtoncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 10, -1, -1));

        jButtonregresar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButtonregresar.setBorderPainted(false);
        jButtonregresar.setContentAreaFilled(false);
        jButtonregresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonregresar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panelbarrasuperior.add(jButtonregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(805, 10, 35, 33));

        getContentPane().add(panelbarrasuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jButtoncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoncerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtoncerrarMouseClicked

    private void jButtonminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonminimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonminimizarMouseClicked

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalirActionPerformed

    private void jbaceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaceptar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbaceptar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        AM am = new AM();
        am.setResizable(false);
        am.setLocationRelativeTo(null);
        am.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jButtoncerrar;
    private javax.swing.JButton jButtonminimizar;
    private javax.swing.JButton jButtonregresar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre10;
    private javax.swing.JLabel jLabelNombre11;
    private javax.swing.JLabel jLabelNombre12;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JLabel jLabelNombre5;
    private javax.swing.JLabel jLabelNombre6;
    private javax.swing.JLabel jLabelNombre7;
    private javax.swing.JLabel jLabelNombre8;
    private javax.swing.JLabel jLabelNombre9;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jbaceptar1;
    private javax.swing.JButton jbsalir;
    private javax.swing.JLabel jlmensajeerror;
    private javax.swing.JLabel jltitulovalidar;
    private javax.swing.JLabel jltitulovalidar1;
    private javax.swing.JTextField jtfcedula;
    private javax.swing.JTextField jtfnombre;
    private javax.swing.JTextField jtfnombre1;
    private javax.swing.JTextField jtfnombre10;
    private javax.swing.JTextField jtfnombre11;
    private javax.swing.JTextField jtfnombre2;
    private javax.swing.JTextField jtfnombre3;
    private javax.swing.JTextField jtfnombre4;
    private javax.swing.JTextField jtfnombre5;
    private javax.swing.JTextField jtfnombre6;
    private javax.swing.JTextField jtfnombre7;
    private javax.swing.JTextField jtfnombre8;
    private javax.swing.JTextField jtfnombre9;
    private javax.swing.JTextField jtfprimerape;
    private javax.swing.JTextField jtfprimerape1;
    private javax.swing.JPanel panelbarrasuperior;
    private javax.swing.JPanel paneldatospersonales;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JPanel panelverificar;
    // End of variables declaration//GEN-END:variables

    private static class SqlUsuarios {

        public SqlUsuarios() {
        }

        private boolean login(Usuarios mod) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class Usuarios {

        public Usuarios() {
        }

        private void setUsuario(String text) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        private void setPassword(String nuevoPass) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }

    private static class txtPassword {

        private static String getPassword() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public txtPassword() {
        }
    }

    private static class Hash {

        private static String sha1(String pass) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Hash() {
        }
    }

    private static class Inicio {

        private static Object frmLog;

        public Inicio() {
        }
    }
}
